services:
  gpg:
    image: cr.galenguyer.com/nginx/php:latest
    container_name: gpg
    restart: unless-stopped
    entrypoint: ash -c 'apk add gnupg && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf'
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gpg.rule=Host(`gpg.galenguyer.com`)"
      - "traefik.http.routers.gpg.entrypoints=https"
      - "traefik.http.routers.gpg.service=gpg"
      - "traefik.http.routers.gpg-insecure.rule=Host(`gpg.galenguyer.com`)"
      - "traefik.http.routers.gpg-insecure.entrypoints=http"
      - "traefik.http.routers.gpg-insecure.middlewares=tohttps"
      - "traefik.http.services.gpg.loadbalancer.server.port=8080"
    networks:
      - traefik
    volumes:
      - type: bind
        source: /var/www/gpg.galenguyer.com
        target: /var/www/html
        read_only: true
      - type: bind
        source: /root/.gnupg
        target: /var/www/.gnupg
        read_only: true

