services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - "USER_UID=10003"
      - "USER_GID=10003"
    depends_on:
      - traefik
    labels:
      - "traefik.http.routers.gitea-web.rule=Host(`git.galenguyer.com`)"
      - "traefik.http.routers.gitea-web.entrypoints=https"
      - "traefik.http.routers.gitea-web.service=gitea-web"
      - "traefik.http.routers.gitea-web.middlewares=secure,hstsplus"
      - "traefik.http.routers.gitea-insecure.rule=Host(`git.galenguyer.com`)"
      - "traefik.http.routers.gitea-insecure.entrypoints=http"
      - "traefik.http.routers.gitea-insecure.middlewares=tohttps"
      - "traefik.http.services.gitea-web.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=gitea"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh"
      - "traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22"
    networks:
      - traefik
    volumes:
      - type: volume
        source: gitea
        target: /data
      - type: bind
        source: ./config/gitea/conf/app.ini
        target: /data/gitea/conf/app.ini
        read_only: true
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

volumes:
  gitea:
