services:
  media:
    image: cr.galenguyer.com/nginx/fancyindex:latest
    container_name: media
    restart: unless-stopped
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`media.galenguyer.com`)"
      - "traefik.http.routers.media.entrypoints=https"
      - "traefik.http.routers.media.middlewares=friendauth"
      - "traefik.http.routers.media.service=media"
      - "traefik.http.routers.media-insecure.rule=Host(`media.galenguyer.com`)"
      - "traefik.http.routers.media-insecure.entrypoints=http"
      - "traefik.http.routers.media-insecure.middlewares=tohttps"
      - "traefik.http.services.media.loadbalancer.server.port=80"
    networks:
      - traefik
    volumes:
      - type: bind
        source: /tank/media/
        target: /usr/share/nginx/html
        read_only: true
