services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    hostname: stonewall
    network_mode: "host"
    volumes:
      - /tank/docker/plex-config:/config
      - /tank/media:/data
